# Generated by Django 4.1 on 2022-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='search',
            name='times_searched',
            field=models.IntegerField(default=1),
        ),
    ]
